In [1]:
from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
veriler = pd.read_csv("veriler.csv")

In [4]:
veriler

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [5]:
x = veriler.iloc[:,1:4].values  #bağımsız değişkenler

In [6]:
y = veriler.iloc[:,4:].values  #bağımlı

In [7]:
x

array([[130,  30,  10],
       [125,  36,  11],
       [135,  34,  10],
       [133,  30,   9],
       [129,  38,  12],
       [180,  90,  30],
       [190,  80,  25],
       [175,  90,  35],
       [177,  60,  22],
       [185, 105,  33],
       [165,  55,  27],
       [155,  50,  44],
       [160,  58,  39],
       [162,  59,  41],
       [167,  62,  55],
       [174,  70,  47],
       [193,  90,  23],
       [187,  80,  27],
       [183,  88,  28],
       [159,  40,  29],
       [164,  66,  32],
       [166,  56,  42]])

In [8]:
y

array([['e'],
       ['e'],
       ['k'],
       ['k'],
       ['e'],
       ['e'],
       ['e'],
       ['e'],
       ['k'],
       ['e'],
       ['k'],
       ['k'],
       ['k'],
       ['k'],
       ['k'],
       ['e'],
       ['e'],
       ['e'],
       ['e'],
       ['k'],
       ['k'],
       ['k']], dtype=object)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.33 , random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
sc = StandardScaler()

In [12]:
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
logr = LogisticRegression(random_state = 0)
logr.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [15]:
y_pred = logr.predict(X_test)
y_pred

array(['e', 'e', 'e', 'e', 'k', 'e', 'e', 'k'], dtype=object)

In [16]:
y_test

array([['k'],
       ['k'],
       ['k'],
       ['k'],
       ['e'],
       ['k'],
       ['k'],
       ['k']], dtype=object)

In [17]:
# MÜkemmel başarı sdlkgklsdgkjdsjkgjklsdkjdsjkgjksdjkgsdjkgjksdgs

In [18]:
from sklearn.metrics import confusion_matrix  #neleri doğru neleri yanlış bulduğumuzu daha rahat görebilmek için

In [19]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[0, 1],
       [6, 1]])

In [20]:
# mukemmel başarımız burada ortaya çıkıyor :D

In [21]:
from sklearn.neighbors import KNeighborsClassifier

In [22]:
knn = KNeighborsClassifier(n_neighbors = 5 , metric = "minkowski")

In [23]:
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

In [24]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[0, 1],
       [6, 1]])

In [25]:
# doğruluk oranımız çok az

In [26]:
knn = KNeighborsClassifier(n_neighbors = 1 , metric = "minkowski")
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

In [27]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[1, 0],
       [4, 3]])

In [28]:
# Komşu sayısını azalttıkça doğruluk oranı arttı

In [29]:
from sklearn.svm import SVC

In [30]:
svc = SVC(kernel ="linear")

In [31]:
svc.fit(X_train,y_train)

SVC(kernel='linear')

In [32]:
y_pred = svc.predict(X_test)

In [33]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[0, 1],
       [6, 1]])

In [34]:
#başarı oranı düşük çıktı bunun parametreleriyle oynayabiliriz

In [67]:
svc = SVC(kernel ="rbf")
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[1, 0],
       [6, 1]])

In [68]:
#rbf ile başarı oranımızı arttırdık bunun gibi çeşitleri deneyebiliriz

In [69]:
svc = SVC(kernel ="poly")
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[0, 1],
       [7, 0]])

In [70]:
#  poly metotu Tamamen yanlış :)):

Naive Bayes 

In [71]:
from sklearn.naive_bayes import GaussianNB

In [72]:
gnb = GaussianNB()
gnb.fit(X_train,y_train)
y_pred = gnb.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[0, 1],
       [6, 1]])

In [73]:
# her veri setinde uygun değildir 

In [74]:
#2 farklı metot daha vardır fakat bunlar bu veri setine uygun değildir
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import ComplementNB

Desicion Tree

In [75]:
from sklearn.tree import DecisionTreeClassifier

In [76]:
dtc = DecisionTreeClassifier(criterion = "gini")
dtc.fit(X_train,y_train)
y_pred = dtc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[1, 0],
       [5, 2]])

In [77]:
dtc = DecisionTreeClassifier(criterion = "entropy")
dtc.fit(X_train,y_train)
y_pred = dtc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[1, 0],
       [5, 2]])

Random Forest

In [78]:
from sklearn.ensemble import RandomForestClassifier

In [89]:
rfc = RandomForestClassifier(n_estimators = 10,criterion = "gini")
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)
cm = confusion_matrix(y_pred,y_pred)
cm

array([[5, 0],
       [0, 3]])

In [90]:
rfc = RandomForestClassifier(n_estimators = 10,criterion = "entropy")
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)
cm = confusion_matrix(y_pred,y_pred)
cm

array([[6, 0],
       [0, 2]])

In [86]:
# %100 başarı yaptı :)