Social Network Ads veri setinin üzerinde sınıflandırma algoritmaları kullanacağız

In [1]:
from warnings import filterwarnings
filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

In [2]:
veriler = pd.read_csv("Social_Network_Ads.csv")  #verilerimizi yüklüyoruz

In [3]:
veriler.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [4]:
veriler.isnull().sum()  #eksik bir veri olmadığını görebiliyoruz

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [5]:
veriler.describe().T

count          mean           std         min          25%  \
User ID          400.0  1.569154e+07  71658.321581  15566689.0  15626763.75   
Age              400.0  3.765500e+01     10.482877        18.0        29.75   
EstimatedSalary  400.0  6.974250e+04  34096.960282     15000.0     43000.00   
Purchased        400.0  3.575000e-01      0.479864         0.0         0.00   

                        50%         75%         max  
User ID          15694341.5  15750363.0  15815236.0  
Age                    37.0        46.0        60.0  
EstimatedSalary     70000.0     88000.0    150000.0  
Purchased               0.0         1.0         1.0

In [6]:
veriler.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   User ID          400 non-null    int64  
 1   Gender           400 non-null    object 
 2   Age              400 non-null    float64
 3   EstimatedSalary  400 non-null    float64
 4   Purchased        400 non-null    int64  
dtypes: float64(2), int64(2), object(1)
memory usage: 15.8+ KB


Makine öğrenmesi algoritmalarında kullanabilmek için verileri numerik değerlere çevirmeliyiz

In [7]:
veriler=pd.get_dummies(veriler,columns=["Gender"],drop_first=True)

In [8]:
veriler.head() #Cinsiyetleri numerik bir değere çevirdik fakat aralarında bir kademe değeri olmaması için dummies yöntemi kullandım

User ID   Age  EstimatedSalary  Purchased  Gender_Male
0  15624510  19.0          19000.0          0            1
1  15810944  35.0          20000.0          0            1
2  15668575  26.0          43000.0          0            0
3  15603246  27.0          57000.0          0            0
4  15804002  19.0          76000.0          0            1

In [9]:
veriler.corr()

User ID       Age  EstimatedSalary  Purchased  Gender_Male
User ID          1.000000 -0.000721         0.071097   0.007120    -0.025249
Age             -0.000721  1.000000         0.155238   0.622454    -0.073741
EstimatedSalary  0.071097  0.155238         1.000000   0.362083    -0.060435
Purchased        0.007120  0.622454         0.362083   1.000000    -0.042469
Gender_Male     -0.025249 -0.073741        -0.060435  -0.042469     1.000000

Verilerin birbirleriyle olan korelasyonlarına baktığımızda User ID ve Cinsiyetin diğer değişkenlere etkisinin az olduğunu görebiliriz

Verilerimizi tahmin ve Sınıflandırma algoritmalarımda kullanmak üzere alırken cinsiyet ve ID leri almayabiliriz

In [10]:
x = veriler.iloc[:,1:3].values 
y=veriler.iloc[:,3:4].values
# Bağımsız değişkenlerimize  Age EstimatedSalary değerlerini alıyoruz
# Bağımlı değişkene Purchased değerlerini alıyoruz

Verilerimizi istediğimiz durumlara göre aldıktan sonra bunları test ve train olarak parçalıyoruz

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2 , random_state = 0)

Algoritmaların daha rahat çalışabilmesi için verileri ölçeklendiriyoruz

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [13]:
X_train = sc.fit_transform(x_train) 
X_test = sc.fit_transform(x_test)
#test ve train verilerimizi ölçeklendirdik

Başlamadan önce sonuçları daha rahat görmemizi sağlayacak confusion matrix kütüphanesini tanımlayalım

In [14]:
from sklearn.metrics import confusion_matrix

Tahmin değerlerinin başarı oranını incelemek için gereken kütüphaneleri kuralım 

In [15]:
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score,fbeta_score,classification_report

**Algoritmaları kullanmaya başlayabiliriz**

# Logistic Regression

In [16]:
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression(random_state = 0)  
logr.fit(X_train,y_train) #fit komutu ile X_traini y_traine göre eğitiyoruz
y_pred = logr.predict(X_test)  # Öğrendiği bilgilere göre tahmin etmesini istiyoruz

In [17]:
cm = confusion_matrix(y_test,y_pred)  #confusion matrix ile sonucu daha rahat görebiliriz
cm  #sonucu inceliyoruz

array([[52,  6],
       [ 3, 19]])

In [18]:
LogisticRegression = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
LogisticRegression

0.8875

# KNN

In [19]:
from sklearn.neighbors import KNeighborsClassifier


In [20]:
knn = KNeighborsClassifier(n_neighbors=5)  #komşu parametresi default olarak 5 geliyor  #diğer değerler default
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

In [21]:
cm = confusion_matrix(y_test,y_pred)  #confusion matrix ile sonucu daha rahat görebiliriz
cm  #sonucu inceliyoruz

array([[54,  4],
       [ 1, 21]])

In [22]:
KNeighbors = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
KNeighbors

0.9375

n_neighbors parametresini farklı değişkenlerde uygulayarak en iyi çalışan parametreyi bulabiliriz

In [23]:
knn = KNeighborsClassifier(n_neighbors=3)  #komşu parametresi default olarak 5 geliyor
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
cm = confusion_matrix(y_test,y_pred)  
cm

array([[54,  4],
       [ 1, 21]])

In [24]:
KNeighbors = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
KNeighbors

0.9375

In [25]:
knn = KNeighborsClassifier(n_neighbors=10)  #komşu parametresi default olarak 5 geliyor
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
cm = confusion_matrix(y_test,y_pred)  
cm

array([[55,  3],
       [ 1, 21]])

In [26]:
KNeighbors = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
KNeighbors

0.95

In [27]:
# Değişkenlerle oynadığımız zaman aralarında çok büyük bir fark görülmüyor
# Son değişken olarak n_neighbors = 10 parametresi olan algoritmayı kullanıyorum bu sonucu diğerleri ile karşılaştıracağım

# Support Vector Classification

In [28]:
from sklearn.svm import SVC

In [29]:
svc = SVC(kernel ="poly")
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[55,  3],
       [ 5, 17]])

In [30]:
SupportVectorC = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
SupportVectorC

0.9

In [31]:
svc = SVC(kernel ="linear")
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[52,  6],
       [ 3, 19]])

In [32]:
SupportVectorC = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
SupportVectorC

0.8875

In [33]:
svc = SVC(kernel ="rbf")
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[54,  4],
       [ 1, 21]])

In [34]:
SupportVectorC = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
SupportVectorC

0.9375

In [35]:
# 3 farklı parametreyi kullandığımızda aralarında rbf parametresi en yüksek sonucu veriyor
# Karşılaştırma olarak rbf parametresini kullanacağım

# Gaussian Process Classifier

In [36]:
from sklearn.gaussian_process import GaussianProcessClassifier

In [37]:
gps = SVC(kernel ="poly")
gps.fit(X_train,y_train)
y_pred = gps.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[55,  3],
       [ 5, 17]])

In [38]:
GaussianClassifier = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
GaussianClassifier

0.9

# Decision Tree

In [39]:
from sklearn.tree import DecisionTreeClassifier

In [40]:
dtc = DecisionTreeClassifier(criterion = "gini")
dtc.fit(X_train,y_train)
y_pred = dtc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[53,  5],
       [ 2, 20]])

In [41]:
DecisionTreeC = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
DecisionTreeC


0.9125

In [42]:
dtc = DecisionTreeClassifier(criterion = "entropy")
dtc.fit(X_train,y_train)
y_pred = dtc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[53,  5],
       [ 1, 21]])

In [43]:
DecisionTreeC = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
DecisionTreeC

0.925

In [44]:
# 2 farklı parametreden yüksek olanı kaydettik

# Random Forest

In [45]:
from sklearn.ensemble import RandomForestClassifier

In [46]:
rfc = RandomForestClassifier(n_estimators = 10,criterion = "gini")
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[54,  4],
       [ 2, 20]])

In [47]:
RandomForestC = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
RandomForestC


0.925

In [48]:
rfc = RandomForestClassifier(n_estimators = 10,criterion = "entropy")
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[56,  2],
       [ 1, 21]])

In [49]:
RandomForestC = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
RandomForestC

0.9625

In [50]:
# Confusion matrixde sonuçlar tamamen doğru gibi gözükse de accuracy değeri daha doğru bir değer

# Ada Boost

In [51]:
from sklearn.ensemble import AdaBoostClassifier

In [52]:
adab = AdaBoostClassifier(n_estimators=100, random_state=0)
adab.fit(X_train,y_train)
y_pred = adab.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[55,  3],
       [ 4, 18]])

In [53]:
AdaBoostC = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
AdaBoostC


0.9125

In [54]:
# Confusion matrixde sonuçlar tamamen doğru gibi gözükse de accuracy değeri daha doğru bir değer

# Gaussian Naive Bayes

In [55]:
from sklearn.naive_bayes import GaussianNB

In [56]:
gausnb = GaussianNB()
gausnb.fit(X_train,y_train)
y_pred = gausnb.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[54,  4],
       [ 1, 21]])

In [57]:
GaussianNB = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
GaussianNB


0.9375

In [58]:
print("LogisticRegression:", LogisticRegression)
print("KNeighbors:",KNeighbors)
print("Support Vector C:",SupportVectorC)
print("GaussianClassifier:", GaussianClassifier)
print("DecisionTreeC:",DecisionTreeC)
print("RandomForestC:",RandomForestC)
print("GaussianNB:",GaussianNB)
print("AdaBoostC:",AdaBoostC)

LogisticRegression: 0.8875
KNeighbors: 0.95
Support Vector C: 0.9375
GaussianClassifier: 0.9
DecisionTreeC: 0.925
RandomForestC: 0.9625
GaussianNB: 0.9375
AdaBoostC: 0.9125


In [59]:
# Algoritmaların sonuçlarını incelediğimizde en başarılı olanların KNN ve RandomForest olduğunu görebiliriz