Wine veri setinin üzerinde sınıflandırma algoritmaları kullanacağız

In [1]:
from warnings import filterwarnings
filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

In [2]:
veriler = pd.read_csv("Wine.csv")  #verilerimizi yüklüyoruz

In [3]:
veriler

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[178 rows x 14 columns]

In [4]:
veriler.isnull().sum()  #eksik bir veri olmadığını görebiliyoruz

Alcohol                 0
Malic_Acid              0
Ash                     0
Ash_Alcanity            0
Magnesium               0
Total_Phenols           0
Flavanoids              0
Nonflavanoid_Phenols    0
Proanthocyanins         0
Color_Intensity         0
Hue                     0
OD280                   0
Proline                 0
Customer_Segment        0
dtype: int64

In [5]:
veriler.describe().T

count        mean         std     min       25%  \
Alcohol               178.0   13.000618    0.811827   11.03   12.3625   
Malic_Acid            178.0    2.336348    1.117146    0.74    1.6025   
Ash                   178.0    2.366517    0.274344    1.36    2.2100   
Ash_Alcanity          178.0   19.494944    3.339564   10.60   17.2000   
Magnesium             178.0   99.741573   14.282484   70.00   88.0000   
Total_Phenols         178.0    2.295112    0.625851    0.98    1.7425   
Flavanoids            178.0    2.029270    0.998859    0.34    1.2050   
Nonflavanoid_Phenols  178.0    0.361854    0.124453    0.13    0.2700   
Proanthocyanins       178.0    1.590899    0.572359    0.41    1.2500   
Color_Intensity       178.0    5.058090    2.318286    1.28    3.2200   
Hue                   178.0    0.957449    0.228572    0.48    0.7825   
OD280                 178.0    2.611685    0.709990    1.27    1.9375   
Proline               178.0  746.893258  314.907474  278.00  500.5000   
Customer_Segment      178.0    1.938202    0.775035    1.00    1.0000   

                          50%       75%      max  
Alcohol                13.050   13.6775    14.83  
Malic_Acid              1.865    3.0825     5.80  
Ash                     2.360    2.5575     3.23  
Ash_Alcanity           19.500   21.5000    30.00  
Magnesium              98.000  107.0000   162.00  
Total_Phenols           2.355    2.8000     3.88  
Flavanoids              2.135    2.8750     5.08  
Nonflavanoid_Phenols    0.340    0.4375     0.66  
Proanthocyanins         1.555    1.9500     3.58  
Color_Intensity         4.690    6.2000    13.00  
Hue                     0.965    1.1200     1.71  
OD280                   2.780    3.1700     4.00  
Proline               673.500  985.0000  1680.00  
Customer_Segment        2.000    3.0000     3.00

In [6]:
veriler.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Alcohol               178 non-null    float64
 1   Malic_Acid            178 non-null    float64
 2   Ash                   178 non-null    float64
 3   Ash_Alcanity          178 non-null    float64
 4   Magnesium             178 non-null    int64  
 5   Total_Phenols         178 non-null    float64
 6   Flavanoids            178 non-null    float64
 7   Nonflavanoid_Phenols  178 non-null    float64
 8   Proanthocyanins       178 non-null    float64
 9   Color_Intensity       178 non-null    float64
 10  Hue                   178 non-null    float64
 11  OD280                 178 non-null    float64
 12  Proline               178 non-null    int64  
 13  Customer_Segment      178 non-null    int64  
dtypes: float64(11), int64(3)
memory usage: 19.6 KB


In [7]:
veriler.corr()

Alcohol  Malic_Acid       Ash  Ash_Alcanity  Magnesium  \
Alcohol               1.000000    0.094397  0.211545     -0.310235   0.270798   
Malic_Acid            0.094397    1.000000  0.164045      0.288500  -0.054575   
Ash                   0.211545    0.164045  1.000000      0.443367   0.286587   
Ash_Alcanity         -0.310235    0.288500  0.443367      1.000000  -0.083333   
Magnesium             0.270798   -0.054575  0.286587     -0.083333   1.000000   
Total_Phenols         0.289101   -0.335167  0.128980     -0.321113   0.214401   
Flavanoids            0.236815   -0.411007  0.115077     -0.351370   0.195784   
Nonflavanoid_Phenols -0.155929    0.292977  0.186230      0.361922  -0.256294   
Proanthocyanins       0.136698   -0.220746  0.009652     -0.197327   0.236441   
Color_Intensity       0.546364    0.248985  0.258887      0.018732   0.199950   
Hue                  -0.071747   -0.561296 -0.074667     -0.273955   0.055398   
OD280                 0.072343   -0.368710  0.003911     -0.276769   0.066004   
Proline               0.643720   -0.192011  0.223626     -0.440597   0.393351   
Customer_Segment     -0.328222    0.437776 -0.049643      0.517859  -0.209179   

                      Total_Phenols  Flavanoids  Nonflavanoid_Phenols  \
Alcohol                    0.289101    0.236815             -0.155929   
Malic_Acid                -0.335167   -0.411007              0.292977   
Ash                        0.128980    0.115077              0.186230   
Ash_Alcanity              -0.321113   -0.351370              0.361922   
Magnesium                  0.214401    0.195784             -0.256294   
Total_Phenols              1.000000    0.864564             -0.449935   
Flavanoids                 0.864564    1.000000             -0.537900   
Nonflavanoid_Phenols      -0.449935   -0.537900              1.000000   
Proanthocyanins            0.612413    0.652692             -0.365845   
Color_Intensity           -0.055136   -0.172379              0.139057   
Hue                        0.433681    0.543479             -0.262640   
OD280                      0.699949    0.787194             -0.503270   
Proline                    0.498115    0.494193             -0.311385   
Customer_Segment          -0.719163   -0.847498              0.489109   

                      Proanthocyanins  Color_Intensity       Hue     OD280  \
Alcohol                      0.136698         0.546364 -0.071747  0.072343   
Malic_Acid                  -0.220746         0.248985 -0.561296 -0.368710   
Ash                          0.009652         0.258887 -0.074667  0.003911   
Ash_Alcanity                -0.197327         0.018732 -0.273955 -0.276769   
Magnesium                    0.236441         0.199950  0.055398  0.066004   
Total_Phenols                0.612413        -0.055136  0.433681  0.699949   
Flavanoids                   0.652692        -0.172379  0.543479  0.787194   
Nonflavanoid_Phenols        -0.365845         0.139057 -0.262640 -0.503270   
Proanthocyanins              1.000000        -0.025250  0.295544  0.519067   
Color_Intensity             -0.025250         1.000000 -0.521813 -0.428815   
Hue                          0.295544        -0.521813  1.000000  0.565468   
OD280                        0.519067        -0.428815  0.565468  1.000000   
Proline                      0.330417         0.316100  0.236183  0.312761   
Customer_Segment            -0.499130         0.265668 -0.617369 -0.788230   

                       Proline  Customer_Segment  
Alcohol               0.643720         -0.328222  
Malic_Acid           -0.192011          0.437776  
Ash                   0.223626         -0.049643  
Ash_Alcanity         -0.440597          0.517859  
Magnesium             0.393351         -0.209179  
Total_Phenols         0.498115         -0.719163  
Flavanoids            0.494193         -0.847498  
Nonflavanoid_Phenols -0.311385          0.489109  
Proanthocyanins       0.330417         -0.499130  
Color_Intensity       0.316100

Veri setinin korelasyonunu incelediğimizde tüm değerlerin Customer_Segment değerini etkilediğini görebiliyoruz bağımlı değişkan olarak alabiliriz

In [8]:
x = veriler.iloc[:,:13].values 
y=veriler.iloc[:,13:].values
# Bağımsız değişkenlerimizi alıyoruz
# Bağımlı değişkene Customer_Segment değerlerini alıyoruz

Verilerimizi istediğimiz durumlara göre aldıktan sonra bunları test ve train olarak parçalıyoruz

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2 , random_state = 0)

Algoritmaların daha rahat çalışabilmesi için verileri ölçeklendiriyoruz

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [11]:
X_train = sc.fit_transform(x_train) 
X_test = sc.fit_transform(x_test)
#test ve train verilerimizi ölçeklendirdik

Başlamadan önce sonuçları daha rahat görmemizi sağlayacak confusion matrix kütüphanesini tanımlayalım

Tahmin değerlerinin başarı oranını incelemek için gereken kütüphaneleri kuralım 

In [12]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score,fbeta_score,classification_report

# Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression(random_state = 0)  
logr.fit(X_train,y_train) #fit komutu ile X_traini y_traine göre eğitiyoruz
y_pred = logr.predict(X_test)  # Öğrendiği bilgilere göre tahmin etmesini istiyoruz

In [14]:
cm = confusion_matrix(y_test,y_pred)  #confusion matrix ile sonucu daha rahat görebiliriz
cm  #sonucu inceliyoruz

array([[14,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  6]])

In [15]:
LogisticRegression = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
LogisticRegression

0.9722222222222222

# KNN

In [16]:
from sklearn.neighbors import KNeighborsClassifier


In [17]:
knn = KNeighborsClassifier(n_neighbors=5)  #komşu parametresi default olarak 5 geliyor  #diğer değerler default
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

In [18]:
cm = confusion_matrix(y_test,y_pred)  #confusion matrix ile sonucu daha rahat görebiliriz
cm  #sonucu inceliyoruz

array([[14,  0,  0],
       [ 0, 14,  2],
       [ 0,  0,  6]])

In [19]:
KNeighbors = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
KNeighbors

0.9444444444444444

In [20]:
# Farklı parametreler kullanacağım

In [21]:
knn = KNeighborsClassifier(n_neighbors=3)  #komşu parametresi default olarak 5 geliyor
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
cm = confusion_matrix(y_test,y_pred)  
cm

array([[14,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  6]])

In [22]:
KNeighbors = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
KNeighbors

0.9722222222222222

# Support Vector Classification

In [23]:
from sklearn.svm import SVC

In [24]:
svc = SVC(kernel ="poly")
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[11,  3,  0],
       [ 0, 16,  0],
       [ 0,  0,  6]])

In [25]:
SupportVectorC = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
SupportVectorC

0.9166666666666666

In [26]:
svc = SVC(kernel ="linear")
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[14,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  6]])

In [27]:
SupportVectorC = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
SupportVectorC

0.9722222222222222

In [28]:
svc = SVC(kernel ="rbf")
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[14,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  6]])

In [29]:
SupportVectorC = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
SupportVectorC

1.0

In [30]:
#### %100 Başarı oranımızı SUpportVEctor ile yakaladık

# Gaussian Process Classifier

In [31]:
from sklearn.gaussian_process import GaussianProcessClassifier

In [32]:
gps = SVC(kernel ="poly")
gps.fit(X_train,y_train)
y_pred = gps.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[11,  3,  0],
       [ 0, 16,  0],
       [ 0,  0,  6]])

In [33]:
GaussianClassifier = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
GaussianClassifier

0.9166666666666666

# Decision Tree

In [34]:
from sklearn.tree import DecisionTreeClassifier

In [35]:
dtc = DecisionTreeClassifier(criterion = "gini")
dtc.fit(X_train,y_train)
y_pred = dtc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[12,  2,  0],
       [ 1, 14,  1],
       [ 0,  0,  6]])

In [36]:
DecisionTreeC = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
DecisionTreeC


0.8888888888888888

In [37]:
dtc = DecisionTreeClassifier(criterion = "entropy")
dtc.fit(X_train,y_train)
y_pred = dtc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[13,  1,  0],
       [ 0, 15,  1],
       [ 0,  0,  6]])

In [38]:
DecisionTreeC = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
DecisionTreeC

0.9444444444444444

# Random Forest

In [39]:
from sklearn.ensemble import RandomForestClassifier

In [40]:
rfc = RandomForestClassifier(n_estimators = 10,criterion = "gini")
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[14,  0,  0],
       [ 4, 11,  1],
       [ 0,  0,  6]])

In [41]:
RandomForestC = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
RandomForestC


0.8611111111111112

In [42]:
rfc = RandomForestClassifier(n_estimators = 10,criterion = "entropy")
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[14,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  6]])

In [43]:
RandomForestC = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
RandomForestC

0.9722222222222222

In [44]:
# Random forestın entropy parametresi ile %100 başarı elde ettik

# Ada Boost

In [45]:
from sklearn.ensemble import AdaBoostClassifier

In [46]:
adab = AdaBoostClassifier(n_estimators=100, random_state=0)
adab.fit(X_train,y_train)
y_pred = adab.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[14,  0,  0],
       [ 5, 10,  1],
       [ 0,  0,  6]])

In [47]:
AdaBoostC = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
AdaBoostC


0.8333333333333334

# Gaussian Naive Bayes

In [48]:
from sklearn.naive_bayes import GaussianNB

In [49]:
gausnb = GaussianNB()
gausnb.fit(X_train,y_train)
y_pred = gausnb.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
cm

array([[13,  1,  0],
       [ 1, 14,  1],
       [ 0,  0,  6]])

In [50]:
GaussianNB = accuracy_score(y_test,y_pred) #başarı oranımızı görebiliriz
GaussianNB

0.9166666666666666

# Veri setlerini karşılaştıralım

In [51]:
print("LogisticRegression:", LogisticRegression)
print("KNeighbors:",KNeighbors)
print("Support Vector C:",SupportVectorC)
print("GaussianClassifier:", GaussianClassifier)
print("DecisionTreeC:",DecisionTreeC)
print("RandomForestC:",RandomForestC)
print("GaussianNB:",GaussianNB)
print("AdaBoostC:",AdaBoostC)

LogisticRegression: 0.9722222222222222
KNeighbors: 0.9722222222222222
Support Vector C: 1.0
GaussianClassifier: 0.9166666666666666
DecisionTreeC: 0.9444444444444444
RandomForestC: 0.9722222222222222
GaussianNB: 0.9166666666666666
AdaBoostC: 0.8333333333333334


In [52]:
# Support Vector ve Random Forest algoritmalarının burda yüksek başarı elde ettiğini görüyoruz